"""empty message

Revision ID: dbe75ff8d47d
Revises: 
Create Date: 2026-07-22 22:16:39.641332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe75ff8d47d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('index', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_cabinets_index'), 'cabinets', ['index'], unique=False)
    op.create_table('groups',
    sa.Column('index', sa.String(length=6), nullable=False),
    sa.Column('number', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_groups_index'), 'groups', ['index'], unique=False)
    op.create_table('cabinet_redirects',
    sa.Column('from_id', sa.String(length=32), nullable=False),
    sa.Column('to_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['cabinets.index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['cabinets.index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_id')
    )
    op.create_index(op.f('ix_cabinet_redirects_from_id'), 'cabinet_redirects', ['from_id'], unique=False)
    op.create_index(op.f('ix_cabinet_redirects_to_id'), 'cabinet_redirects', ['to_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_index', sa.String(length=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_index'], ['groups.index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lessons_group_index_date', 'lessons', ['group_index', 'date'], unique=False)
    op.create_table('lessons_cabinets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.String(length=32), nullable=False),
    sa.Column('cabinet_index', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.index'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_cabinets_cabinet_id'), 'lessons_cabinets', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_lessons_cabinets_lesson_id'), 'lessons_cabinets', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_cabinets_lesson_id'), table_name='lessons_cabinets')
    op.drop_index(op.f('ix_lessons_cabinets_cabinet_id'), table_name='lessons_cabinets')
    op.drop_table('lessons_cabinets')
    op.drop_index('idx_lessons_group_index_date', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_cabinet_redirects_to_id'), table_name='cabinet_redirects')
    op.drop_index(op.f('ix_cabinet_redirects_from_id'), table_name='cabinet_redirects')
    op.drop_table('cabinet_redirects')
    op.drop_index(op.f('ix_groups_index'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_cabinets_index'), table_name='cabinets')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
