"""empty message

Revision ID: e6756f8c9342
Revises: dbe75ff8d47d
Create Date: 2026-08-17 22:25:17.867796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6756f8c9342'
down_revision: Union[str, Sequence[str], None] = 'dbe75ff8d47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.execute("UPDATE groups SET is_active = false")
    op.alter_column("groups", "is_active", nullable=False, existing_type=sa.Boolean())
    op.create_index(op.f('ix_lessons_date'), 'lessons', ['date'], unique=False)
    op.drop_index(op.f('ix_lessons_cabinets_lesson_id'), table_name='lessons_cabinets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lessons_cabinets_lesson_id'), 'lessons_cabinets', ['lesson_id'], unique=False)
    op.drop_index(op.f('ix_lessons_date'), table_name='lessons')
    op.drop_column('groups', 'is_active')
    # ### end Alembic commands ###
