[project]
name = "schedule-db-models"
version = "0.1.1"
description = "SQLAlchemy model for microservices \"Parser Service\" and \"Schedule API Service\""
authors = [
    {name = "Nikita Bondarev",email = "nikitabondarevvitebsk@gmail.com"}
]
license = "No license"
requires-python = ">=3.12,<3.15"
dependencies = [
    "sqlalchemy (>=2.0.51,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
