"""empty message

Revision ID: 060a09bd729e
Revises: fcbd16d383c7
Create Date: 2026-08-19 18:51:10.449644

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "060a09bd729e"
down_revision: str | Sequence[str] | None = "fcbd16d383c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_user_metadata_key_value_user_id",
        "user_metadata",
        ["key", "value", "user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_metadata_key_value_user_id", table_name="user_metadata")
    # ### end Alembic commands ###
