"""empty message

Revision ID: fcbd16d383c7
Revises:
Create Date: 2026-08-05 12:07:27.129994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcbd16d383c7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.create_table(
        "cabinet_subscribes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("cabinet_index", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cabinet_subscribes_user_id",
        "cabinet_subscribes",
        ["user_id", "cabinet_index"],
        unique=True,
    )
    op.create_table(
        "group_subscribes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("group_index", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_group_subscribes_user_id",
        "group_subscribes",
        ["user_id", "group_index"],
        unique=True,
    )
    op.create_table(
        "user_metadata",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=96), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_metadata_user_id_key",
        "user_metadata",
        ["user_id", "key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_metadata_user_id_key", table_name="user_metadata")
    op.drop_table("user_metadata")
    op.drop_index("idx_group_subscribes_user_id", table_name="group_subscribes")
    op.drop_table("group_subscribes")
    op.drop_index("idx_cabinet_subscribes_user_id", table_name="cabinet_subscribes")
    op.drop_table("cabinet_subscribes")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
