name: CD Staging
on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      api: ${{ steps.filter.outputs.api }}
      bot: ${{ steps.filter.outputs.bot }}
      parser: ${{ steps.filter.outputs.parser }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            api:
              - 'services/service_api/**'
            bot:
              - 'services/service_bot/**'
            parser:
              - 'services/service_parser/**'

  lint-and-test:
    needs: changes
    if: always() && (needs.changes.outputs.api == 'true' || needs.changes.outputs.bot == 'true' || needs.changes.outputs.parser == 'true')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api, bot, parser ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies for ${{ matrix.service }}
        if: fromJSON(needs.changes.outputs[matrix.service]) == true
        run: poetry install
        working-directory: services/service_${{ matrix.service }}

      - name: Run ruff for ${{ matrix.service }}
        if: fromJSON(needs.changes.outputs[matrix.service]) == true
        run: poetry run ruff check .
        working-directory: services/service_${{ matrix.service }}

      - name: Run pytest for ${{ matrix.service }}
        if: fromJSON(needs.changes.outputs[matrix.service]) == true
        run: poetry run pytest ./tests
        working-directory: services/service_${{ matrix.service }}
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"

  build-and-push-images:
    needs: [ changes, lint-and-test ]
    if: success() && (needs.changes.outputs.api == 'true' || needs.changes.outputs.bot == 'true' || needs.changes.outputs.parser == 'true')
    runs-on: self-hosted
    strategy:
      matrix:
        service: [ api, bot, parser ]
    steps:
      - uses: actions/checkout@v4

      - name: Build and push ${{ matrix.service }} image
        if: fromJSON(needs.changes.outputs[matrix.service]) == true
        uses: docker/build-push-action@v5
        with:
          context: services/service_${{ matrix.service }}
          push: 'true'
          tags: 10.0.0.1:5000/service_${{ matrix.service }}:${{ github.sha }}
          build-contexts: |
            patterns=${{ github.workspace }}/libs/patterns
            schedule_db_models=${{ github.workspace }}/libs/schedule_db_models
            system_managers=${{ github.workspace }}/libs/system_managers

